#!/bin/zsh

# Requirements:
#   - GMT 6+
#   - STATION_FILE (Generated by gen_inv_final.py)
# Usage:
#   ./sta_loc.sh STATION_FILE

# 1. Event Parameters 
EQLO=160.324
EQLA=52.512

# 2. Setup Directory
STATION_FILE=$1
OUTPUT_FILE="sta_loc"

if [ ! -s "$STATION_FILE" ]; then
    echo "Usage: $0 <filename>"
    echo "Error: File '$STATION_FILE' not found or is empty."
    exit 1
fi

# 3. GMT Plotting

J=E$EQLO/$EQLA/100/15c

gmt begin $OUTPUT_FILE png E720
    gmt set FORMAT_GEO_MAP=+D
    
    # A. Coastlines
    gmt coast -J$J -Rg -A10000 -Swhite -W0.5p,black

    # B. Epicentral Distance Markers (Circles)
    # 30, 60, 90 degrees
    echo $EQLO $EQLA 60d | gmt plot -SE- -W1p,red
    echo $EQLO $EQLA 120d | gmt plot -SE- -W1p,red
    echo $EQLO $EQLA 180d | gmt plot -SE- -W1p,red

    # C. Labels for Distances
    gmt text -F+f10p,Helvetica-Bold,black -D0c/0.3c << EOF
$EQLO  22.5 30\232
$EQLO  -7.5 60\232
$EQLO -37.5 90\232
EOF
    # D. Stations 
    awk 'NR>1 {print $4, $3}' $STATION_FILE | gmt plot -St0.25c -Gblack -W0.5p,white

    # E. Station Names
    awk 'NR>1 {print $4, $3, $1}' $STATION_FILE | gmt text -F+f2.4p,Helvetica,blue -D0.05c/0.10c

    # F. Epicenter
    echo $EQLO $EQLA | gmt plot -Sa0.8c -Gred -W0.5p,black

gmt end show
